### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by cjfields** [h3abionet/H3ABioNet-ML-glossary#3]
`Data preprocessing` link on main page goes to the RNA-Seq SOP, likely copied over from the original SOP repo.

https://h3abionet.github.io/H3ABioNet-ML-glossary/RNA-Seq-1-0.html

**Comment by codemeleon** [comment]
Hi @cjfields 
We need to remove whole folder `pages/genomics_analysis`. It will resolve the issue.
