### ISSUE TITLE
Fix index.md 

### ISSUE THREAD

**Issue by amelgh** [h3abionet/H3ABioNet-ML-glossary#4]
index.md shows the code of the code of the mind map
https://github.com/h3abionet/H3ABioNet-ML-glossary/blob/master/index.md
Could you please fix this?

**Comment by codemeleon** [comment]
Hi @amelgh 
You are seeing the page in markdown format, not as webpage rendered by "jenkins".  please see page at  https://h3abionet.github.io/H3ABioNet-ML-glossary/

**Comment by amelgh** [comment]
YES, but was wondering if it's possible to change the markdown?

**Comment by codemeleon** [comment]
Nope. :)

**Comment by amelgh** [comment]
okay!
